version: '3'

name: sms-audit-system

services:
  
  # API服务模式
  sms-audit-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sms-audit-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - TZ=Asia/Shanghai
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
    tty: true
    profiles:
      - api


# volumes:
#   postgres-data: 